/*
 * Copyright (C) 2015
 * 
 * 
 * 
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 */

package edu.wright.cs.fa15.ceg3120.concon.common.ui.scheduling;

import edu.wright.cs.fa15.ceg3120.concon.common.net.data.SchedulingData;

/**
 * Description. TODO Fill out.
 * @author Emily
 */
public class TabbedFrame extends javax.swing.JFrame {

	private static final long serialVersionUID = -712852962628067006L;
	private SchedulingData scheduleData;
	
	/**
     * Creates new form TabbedFrame.
     */
    public TabbedFrame() {
        initComponents();
    }

    public SchedulingData getScheduleData() {
		return scheduleData;
	}

	/**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings({ "unchecked", "rawtypes" })
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelInstructions = new javax.swing.JLabel();
        tabbedPane = new javax.swing.JTabbedPane();
        panelPayment = new javax.swing.JPanel();
        panelScheduling = new javax.swing.JPanel();
        comboBoxMonths = new javax.swing.JComboBox();
        comboBoxDays = new javax.swing.JComboBox();
        comboBoxTimes = new javax.swing.JComboBox();
        labelInstructionsSecond = new javax.swing.JLabel();
        buttonSubmit = new javax.swing.JButton();
        panelOverview = new javax.swing.JPanel();
        labelTotal = new javax.swing.JLabel();
        textFieldDollars = new javax.swing.JTextField();
        labelAppointmentTime = new javax.swing.JLabel();
        textFieldTime = new javax.swing.JTextField();
        buttonConfirm = new javax.swing.JButton();
        buttonCancel = new javax.swing.JButton();
        labelChosenContractor = new javax.swing.JLabel();
        textFieldContractor = new javax.swing.JTextField();

        labelInstructions.setText("Select The Month, Day, and Perferred time frame");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout panelPaymentLayout = new javax.swing.GroupLayout(panelPayment);
        panelPayment.setLayout(panelPaymentLayout);
        panelPaymentLayout.setHorizontalGroup(
            panelPaymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 409, Short.MAX_VALUE)
        );
        panelPaymentLayout.setVerticalGroup(
            panelPaymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 272, Short.MAX_VALUE)
        );

        tabbedPane.addTab("Payment", panelPayment);

        comboBoxMonths.setModel(new javax.swing.DefaultComboBoxModel(new String[] { 
          "January", "Feburary", "March", "April", "June", "July", "August", 
          "September", "October", "November", "December" }));

        comboBoxDays.setModel(new javax.swing.DefaultComboBoxModel(new String[] { 
          "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", 
          "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", 
          "26", "27", "28", "29", "30", "31" }));

        comboBoxTimes.setBackground(new java.awt.Color(255, 102, 51));
        comboBoxTimes.setModel(new javax.swing.DefaultComboBoxModel(
        		new String[] { "2:30 - 4:30" }));

        labelInstructionsSecond.setText("Select The Month, Day, and Perferred time frame");

        buttonSubmit.setText("Submit");
        buttonSubmit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonSubmitMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelSchedulingLayout = 
        		new javax.swing.GroupLayout(panelScheduling);
        panelScheduling.setLayout(panelSchedulingLayout);
        panelSchedulingLayout.setHorizontalGroup(
            panelSchedulingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSchedulingLayout.createSequentialGroup()
                .addGroup(panelSchedulingLayout.createParallelGroup(
                		javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelSchedulingLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(comboBoxMonths, javax.swing.GroupLayout.PREFERRED_SIZE, 100, 
                        		javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(comboBoxDays, javax.swing.GroupLayout.PREFERRED_SIZE, 134, 
                        		javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(comboBoxTimes, javax.swing.GroupLayout.PREFERRED_SIZE, 131, 
                        		javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelSchedulingLayout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(labelInstructionsSecond))
                    .addGroup(panelSchedulingLayout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(buttonSubmit)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelSchedulingLayout.setVerticalGroup(
            panelSchedulingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSchedulingLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(labelInstructionsSecond)
                .addGap(18, 18, 18)
                .addGroup(panelSchedulingLayout.createParallelGroup(
                		javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxMonths, javax.swing.GroupLayout.PREFERRED_SIZE, 
                    		javax.swing.GroupLayout.DEFAULT_SIZE, 
                    		javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBoxDays, javax.swing.GroupLayout.PREFERRED_SIZE, 
                    		javax.swing.GroupLayout.DEFAULT_SIZE, 
                    		javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBoxTimes, javax.swing.GroupLayout.PREFERRED_SIZE, 
                    		javax.swing.GroupLayout.DEFAULT_SIZE, 
                    		javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 
                		85, Short.MAX_VALUE)
                .addComponent(buttonSubmit)
                .addGap(59, 59, 59))
        );

        tabbedPane.addTab("Scheduling", panelScheduling);

        labelTotal.setText("Total Payment:");

        textFieldDollars.setText("$");

        labelAppointmentTime.setText("Scheduled Appointment Time:");

        textFieldTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldTimeActionPerformed(evt);
            }
        });

        buttonConfirm.setText("Confirm");
        buttonConfirm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonConfirmMouseClicked(evt);
            }
        });

        buttonCancel.setText("Cancel");
        buttonCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonCancelMouseClicked(evt);
            }
        });

        labelChosenContractor.setText("Contractor Chosen:");

        textFieldContractor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldContractorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelOverviewLayout = new javax.swing.GroupLayout(panelOverview);
        panelOverview.setLayout(panelOverviewLayout);
        panelOverviewLayout.setHorizontalGroup(
            panelOverviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOverviewLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(buttonConfirm)
                .addGap(46, 46, 46)
                .addComponent(buttonCancel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelOverviewLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(panelOverviewLayout.createParallelGroup(
                		javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelOverviewLayout.createSequentialGroup()
                        .addComponent(labelChosenContractor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 
                        		javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(textFieldContractor, javax.swing.GroupLayout.PREFERRED_SIZE, 
                        		93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelOverviewLayout.createSequentialGroup()
                        .addComponent(labelTotal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 
                        		javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(textFieldDollars, javax.swing.GroupLayout.PREFERRED_SIZE, 
                        		93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelOverviewLayout.createSequentialGroup()
                        .addComponent(labelAppointmentTime)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 
                        		50, Short.MAX_VALUE)
                        .addComponent(textFieldTime, javax.swing.GroupLayout.PREFERRED_SIZE, 
                        		93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(90, 90, 90))
        );
        panelOverviewLayout.setVerticalGroup(
            panelOverviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOverviewLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(panelOverviewLayout.createParallelGroup(
                		javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelChosenContractor)
                    .addComponent(textFieldContractor, javax.swing.GroupLayout.PREFERRED_SIZE, 
                    		javax.swing.GroupLayout.DEFAULT_SIZE, 
                    		javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(panelOverviewLayout.createParallelGroup(
                		javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTotal)
                    .addComponent(textFieldDollars, javax.swing.GroupLayout.PREFERRED_SIZE, 
                    		javax.swing.GroupLayout.DEFAULT_SIZE, 
                    		javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(panelOverviewLayout.createParallelGroup(
                		javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelAppointmentTime)
                    .addComponent(textFieldTime, javax.swing.GroupLayout.PREFERRED_SIZE, 
                    		javax.swing.GroupLayout.DEFAULT_SIZE, 
                    		javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 
                		50, Short.MAX_VALUE)
                .addGroup(panelOverviewLayout.createParallelGroup(
                		javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonConfirm)
                    .addComponent(buttonCancel))
                .addGap(41, 41, 41))
        );

        tabbedPane.addTab("Overview", panelOverview);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 
            		400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Description. TODO Fill out.
     * @param evt Event.
     */
    //GEN-FIRST:event_buttonSubmitMouseClicked
    private void buttonSubmitMouseClicked(java.awt.event.MouseEvent evt) { 
        scheduleData = new SchedulingData();
        scheduleData.setMonth((String)comboBoxMonths.getSelectedItem());
        scheduleData.setDay((int) comboBoxDays.getSelectedItem());
        scheduleData.setTimeRange((String)comboBoxTimes.getSelectedItem());
    }//GEN-LAST:event_buttonSubmitMouseClicked
    
    /**
     * Description. TODO Fill out.
     * @param evt Event.
     */
    //GEN-FIRST:event_buttonConfirmMouseClicked
    private void buttonConfirmMouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonConfirmMouseClicked

    /**
     * Description. TODO Fill out.
     * @param evt Event.
     */
    //GEN-FIRST:event_buttonCancelMouseClicked
    private void buttonCancelMouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonCancelMouseClicked

    /**
     * Description. TODO Fill out.
     * @param evt Event.
     */
    //GEN-FIRST:event_textFieldTimeActionPerformed
    private void textFieldTimeActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldTimeActionPerformed

    /**
     * Description. TODO Fill out.
     * @param evt Event.
     */
    //GEN-FIRST:event_textFieldContractorActionPerformed
    private void textFieldContractorActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldContractorActionPerformed

    /**
     * Main entry point.
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : 
            	 javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(
            		TabbedFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(
            		TabbedFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(
            		TabbedFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(
            		TabbedFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TabbedFrame().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonSubmit;
    private javax.swing.JButton buttonConfirm;
    private javax.swing.JButton buttonCancel;
    
    // The combo boxes apparently need to hold a raw type.
    @SuppressWarnings("rawtypes")
	private javax.swing.JComboBox comboBoxMonths;
    @SuppressWarnings("rawtypes")
	private javax.swing.JComboBox comboBoxDays;
    @SuppressWarnings("rawtypes")
    
	private javax.swing.JComboBox comboBoxTimes;
    private javax.swing.JLabel labelInstructions;
    private javax.swing.JLabel labelInstructionsSecond;
    private javax.swing.JLabel labelTotal;
    private javax.swing.JLabel labelAppointmentTime;
    private javax.swing.JLabel labelChosenContractor;
    private javax.swing.JPanel panelPayment;
    private javax.swing.JPanel panelScheduling;
    private javax.swing.JPanel panelOverview;
    private javax.swing.JTabbedPane tabbedPane;
    private javax.swing.JTextField textFieldDollars;
    private javax.swing.JTextField textFieldTime;
    private javax.swing.JTextField textFieldContractor;
    // End of variables declaration//GEN-END:variables
}
